=== alexgm511/lrMobile/database/Bikes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Bikes" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Bikes">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="Shipping_Code" index-key="Shipping_Code " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="Bike" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Short_Description" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Long_Description" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Full_Payment" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="Lowest_Payment" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="Picture_Thumbnail" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Picture_Small" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Picture_Large" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Shipping_Code" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Shipping_Code_Islands" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Shipping_Code_Canada" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Page" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SortOrder" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element ref="Bike_Options" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="Bike_Options">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="Bike_ID" index-key="Bike_ID " primary="no" unique="no" clustered="no"/>
<od:index index-name="BikesBike_Options" index-key="Bike_ID " primary="no" unique="no" clustered="no"/>
<od:index index-name="ID" index-key="ID " primary="no" unique="no" clustered="no"/>
<od:index index-name="SKU_1_Payment_Shipping_Code" index-key="SKU_1_Payment_Handling_Code " primary="no" unique="no" clustered="no"/>
<od:index index-name="SKU_4_Payment_Handling_Code" index-key="SKU_4_Payment_Handling_Code " primary="no" unique="no" clustered="no"/>
<od:index index-name="SKU_4_Payment_Handling_Code1" index-key="SKU_10_Payment_Handling_Code " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="Bike_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="Sex" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="1"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Sizes" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Height" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Inseam" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SKU_1_Payment" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SKU_1_Payment_Price" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="SKU_1_Payment_Desc" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SKU_1_Payment_Handling_Code" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SKU_4_Payment" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SKU_4_Payment_Price" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="SKU_4_Payment_Desc" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SKU_4_Payment_Handling_Code" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SKU_10_Payment" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SKU_10_Payment_Price" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="SKU_10_Payment_Desc" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SKU_10_Payment_Handling_Code" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Picture_Cart" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Active" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="1"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== alexgm511/lrMobile/database/Bikes.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Bikes.xsd" generated="2014-10-20T17:32:13">
<Bikes>
<ID>1</ID>
<Bike>LandRider Deluxe AutoShift</Bike>
<Short_Description>The LandRider Deluxe delivers a comfortable, hassle-free ride with our patented 14 speed AutoShift, a dual suspension system and an upright frame design. Also features a comfort saddle with shock absorbing seat post, 2-inch all terrain tires, direct pull linear brakes and a lightweight frame in champagne color.</Short_Description>
<Long_Description>&lt;img src=&quot;images/landrider/LandRider_01.gif&quot; alt=&quot;LandRider&quot; width=&quot;294&quot; height=&quot;50&quot; /&gt;&lt;p&gt;LandRider is a quality bicycle that regularly sells for $499.80. Through our special TV offer, you&apos;ll receive a $100 rebate direct from the manufacturer when you place your order!&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;images/products/women&apos;s-model-popup.jpg&quot; target=&quot;_blank&quot;&gt;Click 	here&lt;/a&gt; to view the women&apos;s step-through model.&lt;/p&gt;&lt;p&gt;And, if you place your order now, you&apos;ll also receive a $100 component upgrade -- &lt;strong&gt;absolutely FREE!&lt;/strong&gt; You&apos;ll receive the revolutionary new LandRider for just $399.80! The upgrade includes the following high performance components:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;Fully adjustable alloy handlebars&lt;/li&gt;&lt;li&gt;Shimano front derailleur&lt;/li&gt;&lt;li&gt;Alloy pedal crank arms&lt;/li&gt;&lt;li&gt;Alloy suspension seat&lt;/li&gt;&lt;/ul&gt;</Long_Description>
<Full_Payment>399.8</Full_Payment>
<Lowest_Payment>99.95</Lowest_Payment>
<Picture_Thumbnail>products/small_images/landrider.jpg</Picture_Thumbnail>
<Picture_Small>Deluxe-1.png</Picture_Small>
<Picture_Large>Deluxe-1.png</Picture_Large>
<Shipping_Code>LRZ25</Shipping_Code>
<Shipping_Code_Islands>LRZ26</Shipping_Code_Islands>
<Shipping_Code_Canada>LRZ27</Shipping_Code_Canada>
<Page>New</Page>
<SortOrder>1</SortOrder>
<Bike_Options>
<ID>1</ID>
<Bike_ID>1</Bike_ID>
<Sex>M</Sex>
<Sizes>12&quot;</Sizes>
<Height>4&apos;8&quot; to 5&apos;2&quot;</Height>
<Inseam>24&quot; to 26&quot;</Inseam>
<SKU_1_Payment>LRD12ST-4MF</SKU_1_Payment>
<SKU_1_Payment_Price>399.8</SKU_1_Payment_Price>
<SKU_1_Payment_Desc>$399.80 + s/h - Single Payment</SKU_1_Payment_Desc>
<SKU_1_Payment_Handling_Code>LRZFEX06</SKU_1_Payment_Handling_Code>
<SKU_4_Payment>LRD12ST-4MP</SKU_4_Payment>
<SKU_4_Payment_Price>99.95</SKU_4_Payment_Price>
<SKU_4_Payment_Desc>$99.95 + s/h - 4 Monthly Payments</SKU_4_Payment_Desc>
<SKU_4_Payment_Handling_Code>LRZFEX05</SKU_4_Payment_Handling_Code>
<SKU_10_Payment_Price>39.98</SKU_10_Payment_Price>
<SKU_10_Payment_Desc>$39.98 + s/h - 10 Monthly Payments</SKU_10_Payment_Desc>
<SKU_10_Payment_Handling_Code>LRZFEX05</SKU_10_Payment_Handling_Code>
<Picture_Cart>products/DeluxeStepThru_cart.jpg</Picture_Cart>
<Active>Y</Active>
</Bike_Options>
<Bike_Options>
<ID>2</ID>
<Bike_ID>1</Bike_ID>
<Sex>M</Sex>
<Sizes>14&quot;</Sizes>
<Height>5&apos;3&quot; to 5&apos;6&quot;</Height>
<Inseam>27&quot; to 29&quot;</Inseam>
<SKU_1_Payment>LRD14-F04MF</SKU_1_Payment>
<SKU_1_Payment_Price>399.8</SKU_1_Payment_Price>
<SKU_1_Payment_Desc>$399.80 + s/h - Single Payment</SKU_1_Payment_Desc>
<SKU_1_Payment_Handling_Code>LRZFEX06</SKU_1_Payment_Handling_Code>
<SKU_4_Payment>LRD14-F04MP</SKU_4_Payment>
<SKU_4_Payment_Price>99.95</SKU_4_Payment_Price>
<SKU_4_Payment_Desc>$99.95 + s/h - 4 Monthly Payments</SKU_4_Payment_Desc>
<SKU_4_Payment_Handling_Code>LRZFEX05</SKU_4_Payment_Handling_Code>
<SKU_10_Payment_Price>39.98</SKU_10_Payment_Price>
<SKU_10_Payment_Desc>$39.98 + s/h - 10 Monthly Payments</SKU_10_Payment_Desc>
<SKU_10_Payment_Handling_Code>LRZFEX05</SKU_10_Payment_Handling_Code>
<Picture_Cart>products/Deluxe_cart.jpg</Picture_Cart>
<Active>Y</Active>
</Bike_Options>
<Bike_Options>
<ID>3</ID>
<Bike_ID>1</Bike_ID>
<Sex>M</Sex>
<Sizes>17&quot;</Sizes>
<Height>5&apos;7&quot; to 5&apos;11&quot;</Height>
<Inseam>30&quot; to 32&quot;</Inseam>
<SKU_1_Payment>LRD17-F04MF</SKU_1_Payment>
<SKU_1_Payment_Price>399.8</SKU_1_Payment_Price>
<SKU_1_Payment_Desc>$399.80 + s/h - Single Payment</SKU_1_Payment_Desc>
<SKU_1_Payment_Handling_Code>LRZFEX06</SKU_1_Payment_Handling_Code>
<SKU_4_Payment>LRD17-F04MP</SKU_4_Payment>
<SKU_4_Payment_Price>99.95</SKU_4_Payment_Price>
<SKU_4_Payment_Desc>$99.95 + s/h - 4 Monthly Payments</SKU_4_Payment_Desc>
<SKU_4_Payment_Handling_Code>LRZFEX05</SKU_4_Payment_Handling_Code>
<SKU_10_Payment_Price>39.98</SKU_10_Payment_Price>
<SKU_10_Payment_Desc>$39.98 + s/h - 10 Monthly Payments</SKU_10_Payment_Desc>
<SKU_10_Payment_Handling_Code>LRZFEX05</SKU_10_Payment_Handling_Code>
<Picture_Cart>products/Deluxe_cart.jpg</Picture_Cart>
<Active>Y</Active>
</Bike_Options>
<Bike_Options>
<ID>4</ID>
<Bike_ID>1</Bike_ID>
<Sex>M</Sex>
<Sizes>19.5&quot;</Sizes>
<Height>6&apos;0&quot; to 6&apos;3&quot;</Height>
<Inseam>33&quot; to 35&quot;</Inseam>
<SKU_1_Payment>LRD19-F04MF</SKU_1_Payment>
<SKU_1_Payment_Price>399.8</SKU_1_Payment_Price>
<SKU_1_Payment_Desc>$399.80 + s/h - Single Payment</SKU_1_Payment_Desc>
<SKU_1_Payment_Handling_Code>LRZFEX06</SKU_1_Payment_Handling_Code>
<SKU_4_Payment>LRD19-F04MP</SKU_4_Payment>
<SKU_4_Payment_Price>99.95</SKU_4_Payment_Price>
<SKU_4_Payment_Desc>$99.95 + s/h - 4 Monthly Payments</SKU_4_Payment_Desc>
<SKU_4_Payment_Handling_Code>LRZFEX05</SKU_4_Payment_Handling_Code>
<SKU_10_Payment_Price>39.98</SKU_10_Payment_Price>
<SKU_10_Payment_Desc>$39.98 + s/h - 10 Monthly Payments</SKU_10_Payment_Desc>
<SKU_10_Payment_Handling_Code>LRZFEX05</SKU_10_Payment_Handling_Code>
<Picture_Cart>products/Deluxe_cart.jpg</Picture_Cart>
<Active>Y</Active>
</Bike_Options>
<Bike_Options>
<ID>5</ID>
<Bike_ID>1</Bike_ID>
<Sex>M</Sex>
<Sizes>22&quot;</Sizes>
<Height>6&apos;4&quot; to 6&apos;8&quot;</Height>
<Inseam>36&quot; plus</Inseam>
<SKU_1_Payment>LRD22-F04MF</SKU_1_Payment>
<SKU_1_Payment_Price>399.8</SKU_1_Payment_Price>
<SKU_1_Payment_Desc>$399.80 + s/h - Single Payment</SKU_1_Payment_Desc>
<SKU_1_Payment_Handling_Code>LRZFEX06</SKU_1_Payment_Handling_Code>
<SKU_4_Payment>LRD22-F04MP</SKU_4_Payment>
<SKU_4_Payment_Price>99.95</SKU_4_Payment_Price>
<SKU_4_Payment_Desc>$99.95 + s/h - 4 Monthly Payments</SKU_4_Payment_Desc>
<SKU_4_Payment_Handling_Code>LRZFEX05</SKU_4_Payment_Handling_Code>
<SKU_10_Payment_Price>39.98</SKU_10_Payment_Price>
<SKU_10_Payment_Desc>$39.98 + s/h - 10 Monthly Payments</SKU_10_Payment_Desc>
<SKU_10_Payment_Handling_Code>LRZFEX05</SKU_10_Payment_Handling_Code>
<Picture_Cart>products/Deluxe_cart.jpg</Picture_Cart>
<Active>Y</Active>
</Bike_Options>
<Bike_Options>
<ID>7</ID>
<Bike_ID>1</Bike_ID>
<Sex>F</Sex>
<Sizes>12&quot;</Sizes>
<Height>4&apos;8&quot; to 5&apos;2&quot;</Height>
<Inseam>24&quot; to 29&quot;</Inseam>
<SKU_1_Payment>LRD12ST-4WF</SKU_1_Payment>
<SKU_1_Payment_Price>399.8</SKU_1_Payment_Price>
<SKU_1_Payment_Desc>$399.80 + s/h - Single payment</SKU_1_Payment_Desc>
<SKU_1_Payment_Handling_Code>LRZFEX06</SKU_1_Payment_Handling_Code>
<SKU_4_Payment>LRD12ST-4WP</SKU_4_Payment>
<SKU_4_Payment_Price>99.95</SKU_4_Payment_Price>
<SKU_4_Payment_Desc>$99.95 + s/h - 4 Monthly Payments</SKU_4_Payment_Desc>
<SKU_4_Payment_Handling_Code>LRZFEX05</SKU_4_Payment_Handling_Code>
<SKU_10_Payment_Price>39.98</SKU_10_Payment_Price>
<SKU_10_Payment_Desc>$39.98 + s/h - 10 Monthly Payments</SKU_10_Payment_Desc>
<SKU_10_Payment_Handling_Code>LRZFEX05</SKU_10_Payment_Handling_Code>
<Picture_Cart>products/DeluxeStepThru_cart.jpg</Picture_Cart>
<Active>Y</Active>
</Bike_Options>
<Bike_Options>
<ID>8</ID>
<Bike_ID>1</Bike_ID>
<Sex>F</Sex>
<Sizes>15&quot;</Sizes>
<Height>5&apos;3&quot; to 5&apos;8&quot;</Height>
<Inseam>30&quot; to 31&quot;</Inseam>
<SKU_1_Payment>LRD15ST-4WF</SKU_1_Payment>
<SKU_1_Payment_Price>399.8</SKU_1_Payment_Price>
<SKU_1_Payment_Desc>$399.80 + s/h - Single payment</SKU_1_Payment_Desc>
<SKU_1_Payment_Handling_Code>LRZFEX06</SKU_1_Payment_Handling_Code>
<SKU_4_Payment>LRD15ST-4WP</SKU_4_Payment>
<SKU_4_Payment_Price>99.95</SKU_4_Payment_Price>
<SKU_4_Payment_Desc>$99.95 + s/h - 4 Monthly Payments</SKU_4_Payment_Desc>
<SKU_4_Payment_Handling_Code>LRZFEX05</SKU_4_Payment_Handling_Code>
<SKU_10_Payment_Price>39.98</SKU_10_Payment_Price>
<SKU_10_Payment_Desc>$39.98 + s/h - 10 Monthly Payments</SKU_10_Payment_Desc>
<SKU_10_Payment_Handling_Code>LRZFEX05</SKU_10_Payment_Handling_Code>
<Picture_Cart>products/DeluxeStepThru_cart.jpg</Picture_Cart>
<Active>Y</Active>
</Bike_Options>
<Bike_Options>
<ID>9</ID>
<Bike_ID>1</Bike_ID>
<Sex>F</Sex>
<Sizes>17&quot;</Sizes>
<Height>5&apos;9&quot; to 6&apos;1&quot;</Height>
<Inseam>32&quot; to 35&quot;</Inseam>
<SKU_1_Payment>LRD17-F04WF</SKU_1_Payment>
<SKU_1_Payment_Price>399.8</SKU_1_Payment_Price>
<SKU_1_Payment_Desc>$399.80 + s/h - Single payment</SKU_1_Payment_Desc>
<SKU_1_Payment_Handling_Code>LRZFEX06</SKU_1_Payment_Handling_Code>
<SKU_4_Payment>LRD17-F04WP</SKU_4_Payment>
<SKU_4_Payment_Price>99.95</SKU_4_Payment_Price>
<SKU_4_Payment_Desc>$99.95 + s/h - 4 Monthly Payments</SKU_4_Payment_Desc>
<SKU_4_Payment_Handling_Code>LRZFEX05</SKU_4_Payment_Handling_Code>
<SKU_10_Payment_Price>39.98</SKU_10_Payment_Price>
<SKU_10_Payment_Desc>$39.98 + s/h - 10 Monthly Payments</SKU_10_Payment_Desc>
<SKU_10_Payment_Handling_Code>LRZFEX05</SKU_10_Payment_Handling_Code>
<Picture_Cart>products/WomansDeluxe_17_cart.jpg</Picture_Cart>
<Active>Y</Active>
</Bike_Options>
</Bikes>

<Bikes>
<ID>4</ID>
<Bike>LandRider Elite AutoShift</Bike>
